# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_geodensity_wrappers", use_symbols = TRUE, package_name = "geodensity")

#' @usage NULL
#' @useDynLib geodensity, .registration = TRUE
NULL

#' Compute Geodesic Kernel Density Estimate
#'
#' This function calculates kernel density estimates on a geographic grid using geodesic
#' (great-circle) distances. The computation is parallelized across CPU cores using Rayon.
#'
#' @param x_coords Vector of X (longitude) coordinates of data points
#' @param y_coords Vector of Y (latitude) coordinates of data points
#' @param grid_x Vector of X coordinates for the output grid cells
#' @param grid_y Vector of Y coordinates for the output grid cells
#' @param bandwidth_km Bandwidth in kilometers (standard deviation of Gaussian kernel)
#' @return A vector of density values corresponding to the grid points
#' @noRd
geodesic_kde_rust <- function(x_coords, y_coords, grid_x, grid_y, bandwidth_km) .Call(wrap__geodesic_kde_rust, x_coords, y_coords, grid_x, grid_y, bandwidth_km)

#' Compute Adaptive Geodesic Kernel Density Estimate
#'
#' This function calculates adaptive kernel density estimates where bandwidth varies inversely
#' with local point density. The computation uses a two-pass algorithm with parallelization.
#'
#' @param x_coords Vector of X (longitude) coordinates of data points
#' @param y_coords Vector of Y (latitude) coordinates of data points
#' @param grid_x Vector of X coordinates for the output grid cells
#' @param grid_y Vector of Y coordinates for the output grid cells
#' @param pilot_bandwidth_km Pilot bandwidth in kilometers for the first pass
#' @param min_bandwidth_km Minimum bandwidth in kilometers (lower bound for adaptive scaling)
#' @return A vector of adaptive density values corresponding to the grid points
#' @noRd
geodesic_kde_adaptive_rust <- function(x_coords, y_coords, grid_x, grid_y, pilot_bandwidth_km, min_bandwidth_km) .Call(wrap__geodesic_kde_adaptive_rust, x_coords, y_coords, grid_x, grid_y, pilot_bandwidth_km, min_bandwidth_km)

#' Evaluate Leave-One-Out Cross-Validation Log-Likelihood for Multiple Bandwidths
#'
#' Computes the leave-one-out CV score for each bandwidth by computing density at each
#' point using all OTHER points, then averaging log-likelihoods.
#'
#' @param x_coords Vector of X (longitude) coordinates of data points
#' @param y_coords Vector of Y (latitude) coordinates of data points
#' @param bandwidths Vector of bandwidth values (in km) to evaluate
#' @return Vector of log-likelihood scores (one per bandwidth)
#' @noRd
bandwidth_loocv_evaluate <- function(x_coords, y_coords, bandwidths) .Call(wrap__bandwidth_loocv_evaluate, x_coords, y_coords, bandwidths)


# nolint end
