# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_geodensity_wrappers", use_symbols = TRUE, package_name = "geodensity")

#' @usage NULL
#' @useDynLib geodensity, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)


# nolint end
